name: Automated Data Cleaning

on:
  push:
    paths:
      - "data/raw/**"
      - "src/**"
      - "requirements.txt"

  workflow_dispatch:

jobs:
  clean-data:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data cleaning
        run: |
          python src/clean_data.py

      - name: Run tests
        run: |
          pytest
